[tools]
claude = "latest"
codex = "latest"
crush = "latest"
gh = "latest"
go = "latest"
"http:muse" = { version = "latest", url = "https://api.meta.ai/muse-launcher.sh", bin = "muse", version_list_url = "https://api.meta.ai/muse-code/channels/muse-stable", version_json_path = ".version" }
node = "latest"
opencode = "latest"

[settings.upgrade]
auto_prune = false
