#! /bin/bash sh
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Hello! I'm installing your dotfiles..."

# HushLogin
touch $HOME/.hushlogin

if [ ! -d "$HOME/.ssh" ]; then
   read -p "Enter your email for SSH key: " email
   ssh-keygen -t ed25519 -C "$email"
   cat $HOME/.ssh/id_ed25519.pub
fi

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# Homebrew
if ! command -v brew >/dev/null 2>&1
then
    echo "Brew is not installed"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Hammerspoon -- Caps Lock to Esc/Ctrl
rm -rf $HOME/.hammerspoon
ln -s $DOTFILES/hammerspoon $HOME/.hammerspoon

# Ghostty
rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

if ! command -v nvim >/dev/null 2>&1
then
    echo "Nvim is not installed"
    /bin/bash -c "brew install neovim"
fi

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# IdeaVim
ln -sf $DOTFILES/.ideavimrc $HOME/.ideavimrc

# PHPStorm
PHPSTORM_DIR="$HOME/Library/Application Support/JetBrains/PhpStorm2025.3"
if [ -d "$PHPSTORM_DIR" ]; then
    # Color scheme
    ln -sf "$DOTFILES/phpstorm/OneDark.icls" "$PHPSTORM_DIR/colors/OneDark.icls"
    # Keymaps
    mkdir -p "$PHPSTORM_DIR/keymaps"
    ln -sf "$DOTFILES/phpstorm/keymaps/KarlM.xml" "$PHPSTORM_DIR/keymaps/KarlM.xml"
    # Theme plugin (must be copied, not symlinked)
    cp "$DOTFILES/phpstorm/OneDarkTheme/OneDarkTheme.jar" "$PHPSTORM_DIR/plugins/OneDarkTheme.jar"
    # Options
    mkdir -p "$PHPSTORM_DIR/options"
    ln -sf "$DOTFILES/phpstorm/options/ide.general.xml" "$PHPSTORM_DIR/options/ide.general.xml"
    ln -sf "$DOTFILES/phpstorm/options/advancedSettings.xml" "$PHPSTORM_DIR/options/advancedSettings.xml"
fi

if ! command -v nvim >/dev/null 2>&1
then
    echo "Nvim is not installed"
    /bin/bash -c "brew install neovim"
fi

# Neovim dependencies
brew install ripgrep fd fzf

# Lazygit
mkdir -p "$HOME/Library/Application Support/lazygit"
ln -sf $DOTFILES/lazygit/config.yml "$HOME/Library/Application Support/lazygit/config.yml"

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# ZSH Extensions
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# Zsh Config
rm -rf $HOME/.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Fonts
cp $DOTFILES/fonts/MonoLisa/*.ttf $HOME/Library/Fonts/

# Tmux Plugin Manager
rm -rf $HOME/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

if ! command -v tmux >/dev/null 2>&1
then
    echo "Tmux is not installed"
    brew install tmux
fi

echo "I'm done installing your dotfiles. Goodbye!"
