#! /bin/bash sh
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Hello! I'm installing your dotfiles..."

# HushLogin
touch $HOME/.hushlogin

if [ ! -d "$HOME/.ssh" ]; then
   ssh-keygen -t ed25519 -C "karl@karlm.dev"
   cat $HOME/.ssh/id_ed25519.pub
fi

# VS Code
ln -s $DOTFILES/vs_code $HOME/.config/vs_code

# Karabiner -- Keyboard settings for macOS
rm -rf $HOME/.config/karabiner
ln -s $DOTFILES/karabiner $HOME/.config/karabiner

# Raycast
rm -rf $HOME/.config/raycast
ln -s $DOTFILES/raycast $HOME/.config/raycast

# Ghostty
rm -rf $HOME/.config/ghostty
ln -s $DOTFILES/ghostty $HOME/.config/ghostty

# Neovim
rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Vimrc
rm -rf $HOME/.vimrc
rm -rf $HOME/.ideavimrc
ln -s $DOTFILES/vim/vimrc $HOME/.vimrc
ln -s $DOTFILES/vim/ideavimrc $HOME/.ideavimrc

# Git
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# Oh My Zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# ZSH Extensions
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]; then
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# Zsh
rm -rf $HOME/.zshrc
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Homebrew
if ! command -v brew >/dev/null 2>&1
then
    echo "Brew is not installed"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if ! command -v nvim >/dev/null 2>&1
then
    echo "Nvim is not installed"
    /bin/bash -c "brew install neovim"
fi

# Neovim dependencies
brew install ripgrep fd

# Lazygit
mkdir -p "$HOME/Library/Application Support/lazygit"
ln -sf $DOTFILES/lazygit/config.yml "$HOME/Library/Application Support/lazygit/config.yml"

# Fonts
cp $DOTFILES/fonts/MonoLisa/*.ttf $HOME/Library/Fonts/

# Tmux Plugin Manager
rm -rf $HOME/.tmux
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Tmux
rm -rf $HOME/.tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

if ! command -v tmux >/dev/null 2>&1
then
    echo "Tmux is not installed"
    brew install tmux
fi

echo "I'm done installing your dotfiles. Goodbye!"
