export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#757575'
ZSH_AUTOSUGGEST_HISTORY_IGNORE="nvr *"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

setopt HIST_IGNORE_SPACE

export HOMEBREW_NO_ENV_HINTS=1

export PATH="$HOME/.local/bin:$PATH:$HOME/.composer/vendor/bin:$HOME/.config/composer/vendor/bin"

export DOTFILES="$HOME/dotfiles"
export XDG_CONFIG_HOME="$HOME/.config"

export SUDO_ASKPASS="$DOTFILES/scripts/askpass.sh"

source <(fzf --zsh)

source "$XDG_CONFIG_HOME/zsh/aliases.sh"

