hl.unbind("SUPER + W")
hl.unbind("SUPER + T")
hl.unbind("SUPER + F")
hl.unbind("SUPER + SHIFT + BACKSPACE")
hl.unbind("SUPER + SHIFT + S")
hl.unbind("SUPER + SHIFT + M")
hl.unbind("XF86MonBrightnessUp")
hl.unbind("XF86MonBrightnessDown")
hl.unbind("SHIFT + XF86MonBrightnessUp")
hl.unbind("SHIFT + XF86MonBrightnessDown")
hl.unbind("ALT + XF86MonBrightnessUp")
hl.unbind("ALT + XF86MonBrightnessDown")
hl.unbind("CTRL + ALT + DELETE")
hl.unbind("SUPER + J")
hl.unbind("SUPER + P")
hl.unbind("SUPER + CTRL + F")
hl.unbind("SUPER + ALT + F")
hl.unbind("SUPER + O")
hl.unbind("SUPER + ALT + Home")
hl.unbind("SUPER + Home")
hl.unbind("SUPER + L")
hl.unbind("SUPER + S")
hl.unbind("SUPER + ALT + S")
hl.unbind("SUPER + TAB")
hl.unbind("SUPER + SHIFT + TAB")
hl.unbind("SUPER + CTRL + TAB")
hl.unbind("SUPER + SHIFT + ALT + LEFT")
hl.unbind("SUPER + SHIFT + ALT + RIGHT")
hl.unbind("SUPER + SHIFT + ALT + UP")
hl.unbind("SUPER + SHIFT + ALT + DOWN")
hl.unbind("ALT + TAB")
hl.unbind("ALT + SHIFT + TAB")
hl.unbind("SUPER + ALT + code:20")
hl.unbind("SUPER + ALT + code:21")
hl.unbind("SUPER + SHIFT + ALT + code:20")
hl.unbind("SUPER + SHIFT + ALT + code:21")
hl.unbind("SUPER + CTRL + code:20")
hl.unbind("SUPER + CTRL + code:21")
hl.unbind("SUPER + CTRL + SHIFT + code:20")
hl.unbind("SUPER + CTRL + SHIFT + code:21")
hl.unbind("SUPER + mouse_down")
hl.unbind("SUPER + mouse_up")
hl.unbind("SUPER + G")
hl.unbind("SUPER + ALT + G")
hl.unbind("SUPER + ALT + LEFT")
hl.unbind("SUPER + ALT + RIGHT")
hl.unbind("SUPER + ALT + UP")
hl.unbind("SUPER + ALT + DOWN")
hl.unbind("SUPER + ALT + TAB")
hl.unbind("SUPER + ALT + SHIFT + TAB")
hl.unbind("SUPER + CTRL + LEFT")
hl.unbind("SUPER + CTRL + RIGHT")
hl.unbind("SUPER + ALT + mouse_down")
hl.unbind("SUPER + ALT + mouse_up")
hl.unbind("SUPER + ALT + code:10")
hl.unbind("SUPER + ALT + code:11")
hl.unbind("SUPER + ALT + code:12")
hl.unbind("SUPER + ALT + code:13")
hl.unbind("SUPER + ALT + code:14")
hl.unbind("SUPER + SLASH")
hl.unbind("SUPER + ALT + SLASH")
hl.unbind("SUPER + SHIFT + RETURN")
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + SHIFT + N")
hl.unbind("SUPER + ALT + RETURN")
hl.unbind("SUPER + SHIFT + G")
hl.unbind("SUPER + SHIFT + O")
hl.unbind("SUPER + SHIFT + W")
hl.unbind("SUPER + SHIFT + A")
hl.unbind("SUPER + SHIFT + ALT + A")
hl.unbind("SUPER + SHIFT + C")
hl.unbind("SUPER + SHIFT + E")
hl.unbind("SUPER + SHIFT + ALT + E")
hl.unbind("SUPER + SHIFT + Y")
hl.unbind("SUPER + SHIFT + ALT + G")
hl.unbind("SUPER + SHIFT + CTRL + G")
hl.unbind("SUPER + SHIFT + P")
hl.unbind("SUPER + ALT + SPACE")
hl.unbind("SUPER + CTRL + C")
hl.unbind("SUPER + CTRL + H")
hl.unbind("SUPER + SHIFT + code:201")
hl.unbind("SUPER + ALT + K")
hl.unbind("SUPER + CTRL + Q")
hl.unbind("XF86Calculator")
hl.unbind("SUPER + SHIFT + SPACE")
hl.unbind("SUPER + BACKSPACE")
hl.unbind("SUPER + CTRL + BACKSPACE")
hl.unbind("SUPER + SHIFT + comma")
hl.unbind("SUPER + CTRL + comma")
hl.unbind("SUPER + SHIFT + ALT + comma")
hl.unbind("SUPER + CTRL + I")
hl.unbind("SUPER + CTRL + N")
hl.unbind("SUPER + CTRL + Delete")
hl.unbind("SUPER + CTRL + ALT + Delete")
hl.unbind("PRINT")
hl.unbind("SUPER + ALT + code:34")
hl.unbind("SUPER + ALT + code:35")
hl.unbind("SUPER + CTRL + PRINT")
hl.unbind("SUPER + CTRL + S")
hl.unbind("SUPER + CTRL + PERIOD")
hl.unbind("SUPER + CTRL + R")
hl.unbind("SUPER + CTRL + ALT + R")
hl.unbind("SUPER + SHIFT + CTRL + R")
hl.unbind("SUPER + CTRL + ALT + T")
hl.unbind("SUPER + CTRL + ALT + B")
hl.unbind("SUPER + CTRL + ALT + W")
hl.unbind("SUPER + CTRL + A")
hl.unbind("SUPER + CTRL + B")
hl.unbind("SUPER + CTRL + D")
hl.unbind("SUPER + CTRL + ALT + D")
hl.unbind("SUPER + CTRL + W")
hl.unbind("SUPER + CTRL + P")
hl.unbind("SUPER + CTRL + code:10")
hl.unbind("SUPER + CTRL + code:11")
hl.unbind("SUPER + CTRL + code:12")
hl.unbind("SUPER + CTRL + code:13")
hl.unbind("SUPER + CTRL + code:14")
hl.unbind("SUPER + CTRL + code:15")
hl.unbind("SUPER + CTRL + code:16")
hl.unbind("SUPER + CTRL + code:17")
hl.unbind("SUPER + CTRL + code:18")
hl.unbind("SUPER + CTRL + Z")
hl.unbind("SUPER + CTRL + ALT + Z")
hl.unbind("XF86KbdBrightnessUp")
hl.unbind("XF86KbdBrightnessDown")
hl.unbind("XF86KbdLightOnOff")
hl.unbind("XF86TouchpadToggle")
hl.unbind("XF86TouchpadOn")
hl.unbind("XF86TouchpadOff")
hl.unbind("XF86AudioNext")
hl.unbind("ALT + XF86AudioPlay")
hl.unbind("XF86AudioPause")
hl.unbind("XF86AudioPlay")
hl.unbind("XF86AudioPrev")
hl.unbind("ALT + SHIFT + XF86AudioPlay")
hl.unbind("XF86Eject")
hl.unbind("SHIFT + XF86AudioMute")
hl.unbind("SHIFT + XF86AudioPause")
hl.unbind("SHIFT + XF86AudioPlay")
hl.unbind("SUPER + CTRL + V")
hl.unbind("F9")
hl.unbind("SUPER + ALT + SHIFT + F")
hl.unbind("SUPER + comma")
hl.unbind("ALT + PRINT")
hl.unbind("SUPER + PRINT")
hl.unbind("SUPER + SHIFT + code:10")
hl.unbind("SUPER + SHIFT + code:11")
hl.unbind("SUPER + SHIFT + code:12")
hl.unbind("SUPER + SHIFT + code:13")
hl.unbind("SUPER + SHIFT + code:14")
hl.unbind("SUPER + SHIFT + code:15")
hl.unbind("SUPER + SHIFT + code:16")
hl.unbind("SUPER + SHIFT + code:17")
hl.unbind("SUPER + SHIFT + code:18")
hl.unbind("SUPER + SHIFT + code:19")

local function send_shortcut_once(mods, key)
  hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down" }))

  hl.timer(function()
    hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up" }))
  end, { timeout = 50, type = "oneshot" })
end

local function active_window_is_terminal()
  local window = hl.get_active_window()
  if not window then
    return false
  end

  for _, tag in ipairs(window.tags or {}) do
    if tag:gsub("%*$", "") == "terminal" then
      return true
    end
  end

  return false
end

o.bind("SUPER + Q", "Close window", hl.dsp.window.close())

for workspace = 1, 9 do
  o.bind("CTRL + SHIFT + code:" .. tostring(workspace + 9), "Move window to workspace " .. workspace, hl.dsp.window.move({ workspace = tostring(workspace) }))
end

o.bind("SUPER + A", "Universal select all", function()
  if active_window_is_terminal() then
    send_shortcut_once("CTRL SHIFT", "A")
  else
    send_shortcut_once("CTRL", "A")
  end
end)

o.bind("SUPER + S", "Universal save", function()
  send_shortcut_once("CTRL", "S")
end)

o.bind("SUPER + SHIFT + F", "File manager (cwd)", "omarchy-launch-terminal spf")

o.bind("SUPER + comma", "Dismiss all notifications", "omarchy-shell notifications dismissAll")

o.bind("SUPER + SHIFT + code:13", "Screenshot", "omarchy-capture-screenshot")
o.bind("SUPER + SHIFT + code:14", "Screenrecording", "omarchy-capture-screenrecording --stop-recording || omarchy-menu toggle trigger.capture.screenrecord")
o.bind("SUPER + CTRL + code:15", "Color picker", "pkill hyprpicker || hyprpicker -a")

o.bind("SUPER + SHIFT + M", "Apple Music", "omarchy-launch-or-focus-webapp 'chrome-music\\.apple' https://music.apple.com/us/new")

o.bind("XF86MonBrightnessUp", "Brightness up", "brightness-all-displays +5%", { locked = true, repeating = true })
o.bind("XF86MonBrightnessDown", "Brightness down", "brightness-all-displays 5%-", { locked = true, repeating = true })
o.bind("SHIFT + XF86MonBrightnessUp", "Brightness maximum", "brightness-all-displays 100%", { locked = true, repeating = true })
o.bind("SHIFT + XF86MonBrightnessDown", "Brightness minimum", "brightness-all-displays 1%", { locked = true, repeating = true })
o.bind("ALT + XF86MonBrightnessUp", "Brightness up precise", "brightness-all-displays +1%", { locked = true, repeating = true })
o.bind("ALT + XF86MonBrightnessDown", "Brightness down precise", "brightness-all-displays 1%-", { locked = true, repeating = true })
