theme[main_bg]="#282c34"
theme[main_fg]="#dcdfe4"
theme[title]="#dcdfe4"
theme[hi_fg]="#61afef"
theme[selected_bg]="#474e5d"
theme[selected_fg]="#dcdfe4"
theme[inactive_fg]="#5d677a"
theme[graph_text]="#5d677a"
theme[meter_bg]="#3e4452"
theme[proc_misc]="#98c379"

theme[cpu_box]="#61afef"
theme[mem_box]="#98c379"
theme[net_box]="#c678dd"
theme[proc_box]="#56b6c2"
theme[div_line]="#5d677a"

theme[temp_start]="#98c379"
theme[temp_mid]="#e5c07b"
theme[temp_end]="#e06c75"

theme[cpu_start]="#98c379"
theme[cpu_mid]="#e5c07b"
theme[cpu_end]="#e06c75"

theme[free_start]="#98c379"
theme[free_mid]="#56b6c2"
theme[free_end]="#61afef"

theme[cached_start]="#61afef"
theme[cached_mid]="#56b6c2"
theme[cached_end]="#c678dd"

theme[available_start]="#56b6c2"
theme[available_mid]="#61afef"
theme[available_end]="#c678dd"

theme[used_start]="#98c379"
theme[used_mid]="#e5c07b"
theme[used_end]="#e06c75"

theme[download_start]="#98c379"
theme[download_mid]="#56b6c2"
theme[download_end]="#61afef"

theme[upload_start]="#e5c07b"
theme[upload_mid]="#e06c75"
theme[upload_end]="#c678dd"

theme[process_start]="#98c379"
theme[process_mid]="#e5c07b"
theme[process_end]="#e06c75"
