onboarding = false

[theme]
name = "one-dark"
auto_switch = true
dark_name = "one-dark"
light_name = "one-light"

[ui]
hide_tab_bar_when_single_tab = true
pane_borders = "off"

[ui.toast]
delivery = "system"

[[keys.command]]
key = "prefix+alt+c"
type = "shell"
command = "~/.local/bin/herdr-tabs"
