onboarding = false

[theme]
name = "one-dark"
auto_switch = true
dark_name = "one-dark"
light_name = "one-light"

[theme.custom]
panel_bg = "black"

[terminal]
new_cwd = "follow"

[ui]
accent = "blue"

confirm_close = true

hide_tab_bar_when_single_tab = true

mouse_capture = true

pane_gaps = true
pane_outer_borders = true
pane_borders = "auto"
pane_scrollbars = false

prompt_new_tab_name = false

sidebar_collapsed_mode="hidden"

tab_bar_right = [{ type = "zoom" }]
tab_bar_position = "bottom"

window_title = "{hostname}: {workspace}"

[ui.toast]
delivery = "system"

[[keys.command]]
key = "prefix+alt+c"
type = "shell"
command = "~/.local/bin/herdr-tabs"
