export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

DISABLE_AUTO_TITLE="true"

plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"

# OS
alias yeet="sudo rm -rf"
alias vim="nvim"
alias ps="phpstorm"
alias brewup="brew update && brew upgrade && brew upgrade --greedy && open /Applications/Raycast.app/"

# Laravel
alias a="php artisan"
alias pam="php artisan migrate"
alias pamf="php artisan migrate:fresh"
alias mfs="php artisan migrate:fresh --seed"
alias pail="php artisan pail"

alias pass="cd ~/code/api.foxworldtravel && php artisan passport:install"
alias atf="a test --filter"

# Laravel Vendor
alias dust="./vendor/bin/duster fix"
alias duster="./vendor/bin/duster"
alias stan="./vendor/bin/phpstan analyze -c larastan.neon"
alias pest="./vendor/bin/pest"
alias pint="./vendor/bin/pint"

# NPM 
alias watch="npm run watch"
alias prod="npm run production"
alias dev="npm run dev"
alias build="npm run build"

# Python
alias python="python3"
alias pip="pip3"
