export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

DISABLE_AUTO_TITLE="true"

plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export NVM_DIR="$HOME/.nvm"

alias stan="./vendor/bin/phpstan analyze -c larastan.neon"
alias pest="./vendor/bin/pest"
alias mfs="php artisan migrate:fresh --seed"
alias pass="cd ~/code/api.foxworldtravel && php artisan passport:install"
alias a="php artisan"
alias pam="php artisan migrate"
alias pamf="php artisan migrate:fresh"

alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'
alias pint="./vendor/bin/pint"
alias vim="nvim"
alias watch="npm run watch"
alias prod="npm run production"
alias yeet="sudo rm -rf"
alias dev="npm run dev"
alias build="npm run build"
alias atf="a test --filter"
alias python="python3"
alias pip="pip3"
alias brewup="brew update && brew upgrade && brew upgrade --greedy && open /Applications/Raycast.app/"
alias dust="./vendor/bin/duster fix"
alias duster="./vendor/bin/duster "
alias ps="phpstorm"
alias pail="php artisan pail"
